FROM quay.io/redhat-user-workloads/konflux-jbs-pnc-tenant/jvm-build-service-builder-images/ubi8:67236e7041a57cd8e31a6f890b0155bc0a1c1700
USER 0
WORKDIR /var/workdir
ARG PROXY_URL=""
ENV PROXY_URL=$PROXY_URL
COPY .jbs/run-build.sh /var/workdir
COPY . /var/workdir/workspace/source/
RUN /var/workdir/run-build.sh
FROM scratch
COPY --from=0 /var/workdir/workspace/artifacts /
